# Generated by Django 5.2.6 on 2025-09-24 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=100)),
                ('airport_iata', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_iata', models.CharField(max_length=10)),
                ('flight_icao', models.CharField(max_length=10)),
                ('airline_name', models.CharField(max_length=100)),
                ('airline_iata', models.CharField(max_length=10)),
                ('airline_icao', models.CharField(max_length=10)),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_scheduled', models.DateTimeField()),
                ('arrival_scheduled', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='frontend.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='frontend.airport')),
            ],
        ),
    ]
