# Generated by Django 5.2.6 on 2025-09-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='arrival_airport',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='arrival_scheduled',
            new_name='HChegada',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='departure_scheduled',
            new_name='HPartida',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='airline_iata',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='airline_icao',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='airline_name',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='flight_iata',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='flight_icao',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='status',
        ),
        migrations.AddField(
            model_name='flights',
            name='ADestino',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='AOrigem',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='Companhia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flights',
            name='DCidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flights',
            name='OCidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flights',
            name='Preco',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='Voo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='airport',
        ),
    ]
