# Generated by Django 5.2.6 on 2025-09-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_flights_departure_airport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='ADestino',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='AOrigem',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='Companhia',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='DCidade',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='HChegada',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='HPartida',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='OCidade',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='Preco',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='Voo',
        ),
        migrations.AddField(
            model_name='flights',
            name='airline_iata',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='airline_icao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='airline_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='arrival_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='departure_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='departure_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='flight_iata',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='flight_icao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
