# Generated by Django 5.2.6 on 2025-09-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_flights_adestino_remove_flights_aorigem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='arrival_iata',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='departure_iata',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='airline_iata',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='flight_iata',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
