# Generated by Django 5.2.6 on 2025-09-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_flights_arrival_iata_flights_departure_iata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrival_iata',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_iata',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='flight_iata',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
